import express from 'express';
import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { createServer as createViteServer } from 'vite';
const app=express(); app.use(express.json()); const PORT=5173; const file=path.resolve('state.json'); const now=()=>new Date().toISOString();
const seed=()=>({school:{name:'Gläntanskolan',role:'Skolledare',user:'Daniel'},challenges:[
{id:'lesson',title:'Lektionsstruktur',question:'Hur skapar vi en mer förutsägbar, engagerande och effektiv lektionsstart?',category:'Undervisning',color:'violet',status:'Pågående'},
{id:'attendance',title:'Närvaro',question:'Hur upptäcker och agerar vi tidigare på problematisk frånvaro?',category:'Elevhälsa',color:'blue',status:'Pågående'},
{id:'study',title:'Studiero',question:'Vilka gemensamma strukturer ökar elevernas fokus under lektionstid?',category:'Lärmiljö',color:'green',status:'Utforskar'},
{id:'transition',title:'Övergångar',question:'Hur minskar vi tappet mellan lektioner och får snabbare omstarter?',category:'Organisation',color:'orange',status:'Utforskar'}],nodes:[
{id:'n1',challengeId:'lesson',type:'problem',title:'Problem',body:'Elever kommer inte igång snabbt efter lektionsstart.',x:60,y:170},{id:'n2',challengeId:'lesson',type:'observation',title:'Observation',body:'Olika lärare startar lektionen på helt olika sätt.',x:300,y:170},{id:'n3',challengeId:'lesson',type:'hypothesis',title:'Hypotes',body:'En gemensam startstruktur skulle kunna minska startsträckan.',x:540,y:170},{id:'n4',challengeId:'lesson',type:'experiment',title:'Experiment',body:'Testa 5-minutersmodellen i 7A och 7B.',x:780,y:170},{id:'n5',challengeId:'lesson',type:'learning',title:'Lärande',body:'Tydlig start fungerar, men instruktionen behöver visas visuellt.',x:1020,y:170},
{id:'a1',challengeId:'attendance',type:'problem',title:'Problem',body:'Frånvaromönster upptäcks ibland först när de blivit omfattande.',x:80,y:190},{id:'a2',challengeId:'attendance',type:'experiment',title:'Experiment',body:'Testa gemensam veckovis signalspaning i mentorslagen.',x:340,y:190},{id:'s1',challengeId:'study',type:'problem',title:'Problem',body:'Studieron varierar kraftigt mellan lektioner och grupper.',x:80,y:190},{id:'t1',challengeId:'transition',type:'problem',title:'Problem',body:'Många elever kommer sent efter raster och salbyten.',x:80,y:190}],links:[
{id:'l1',challengeId:'lesson',from:'n1',to:'n2'},{id:'l2',challengeId:'lesson',from:'n2',to:'n3'},{id:'l3',challengeId:'lesson',from:'n3',to:'n4'},{id:'l4',challengeId:'lesson',from:'n4',to:'n5'}],models:[
{id:'backa',school:'Bäckaskolan',title:'Gemensam lektionsstart – 3 steg',question:'Hur skapar vi en konsekvent och snabb start i alla klassrum?',category:'Undervisning',grades:'åk 7–9',experiments:4,revisions:2,quote:'Vi minskade starttiden genom en tydlig visuell rutin och samma grundstruktur i alla ämnen.',tags:['lektionsstart','visuell instruktion','studiero'],steps:[['problem','Problem','Lång startsträcka och otydlighet i början.'],['observation','Antagande','Olika startmönster skapar osäkerhet.'],['hypothesis','Hypotes','Tre fasta steg skapar förutsägbarhet.'],['experiment','Experiment','Test i åk 7–9 under sex veckor.'],['learning','Resultat','Fler elever var igång inom fem minuter.'],['next','Rekommendation','Behåll samma visuella startkort mellan ämnen.']]},
{id:'linde',school:'Lindeskolan',title:'Startkort för varje ämne',question:'Hur kan elever veta exakt vad som ska hända de första fem minuterna?',category:'Undervisning',grades:'åk 4–9',experiments:3,revisions:1,quote:'Eleverna vet exakt vad som ska hända första fem minuterna.',tags:['startkort','struktur'],steps:[['problem','Problem','Muntlig information försvinner vid lektionsstart.'],['hypothesis','Hypotes','Ett synligt startkort minskar upprepningar.'],['experiment','Experiment','Startkort i tre ämnen under fyra veckor.'],['learning','Lärande','Samma layout mellan ämnen fungerade bäst.']]},
{id:'tall',school:'Tallskolan',title:'Lärarledd start med gemensam timer',question:'Kan en gemensam timer skapa tempo och tydlighet?',category:'Lärmiljö',grades:'åk 6–9',experiments:2,revisions:2,quote:'En enkel timer och tre fasta steg gjorde stor skillnad.',tags:['timer','studiero'],steps:[['problem','Problem','Lektionen tar lång tid att samla.'],['hypothesis','Hypotes','Femminuterstimer skapar tempo.'],['experiment','Experiment','Test i sex klasser.'],['learning','Lärande','Timer fungerade som stöd, inte kontroll.']]},
{id:'sjo',school:'Sjöängsskolan',title:'Tidiga frånvarosignaler i mentorslaget',question:'Hur fångar vi mönster innan frånvaron blivit hög?',category:'Elevhälsa',grades:'åk 7–9',experiments:5,revisions:3,quote:'Veckovis signalspaning gjorde mönster synliga tidigare.',tags:['närvaro','mentor'],steps:[['problem','Problem','Korttidsfrånvaro syns sent.'],['observation','Observation','Mentorer tolkar data olika.'],['experiment','Experiment','10 min signalspaning varje vecka.'],['learning','Lärande','Få, tydliga signaler blev hållbart.']]}
]});
let state; try{state=JSON.parse(fs.readFileSync(file,'utf8'))}catch{state=seed();} const save=()=>{try{fs.writeFileSync(file,JSON.stringify(state,null,2))}catch{}};
const detail=id=>{const c=state.challenges.find(x=>x.id===id); return c?{...c,nodes:state.nodes.filter(n=>n.challengeId===id),links:state.links.filter(l=>l.challengeId===id)}:null};
app.get('/api/dashboard',(_,r)=>r.json({school:state.school,activeChallenges:state.challenges.length,experiments:state.nodes.filter(n=>n.type==='experiment').length,learnings:state.nodes.filter(n=>n.type==='learning').length,networkModels:state.models.length}));
app.get('/api/challenges',(_,r)=>r.json(state.challenges)); app.get('/api/challenges/:id',(q,r)=>{const d=detail(q.params.id);d?r.json(d):r.sendStatus(404)});
app.post('/api/challenges',(q,r)=>{const item={id:randomUUID(),title:q.body.title,question:q.body.question,category:q.body.category||'Övrigt',color:q.body.color||'violet',status:'Utforskar'};state.challenges.push(item);save();r.status(201).json(item)});
app.post('/api/challenges/:id/nodes',(q,r)=>{const ns=state.nodes.filter(n=>n.challengeId===q.params.id);const n={id:randomUUID(),challengeId:q.params.id,type:q.body.type||'idea',title:q.body.title||'Ny nod',body:q.body.body||'',x:q.body.x??80+ns.length*240,y:q.body.y??170};state.nodes.push(n);if(q.body.fromNodeId)state.links.push({id:randomUUID(),challengeId:q.params.id,from:q.body.fromNodeId,to:n.id});save();r.status(201).json(n)});
app.patch('/api/nodes/:id',(q,r)=>{const n=state.nodes.find(x=>x.id===q.params.id);if(!n)return r.sendStatus(404);Object.assign(n,q.body,{id:n.id,challengeId:n.challengeId});save();r.json(n)});
app.delete('/api/nodes/:id',(q,r)=>{state.nodes=state.nodes.filter(n=>n.id!==q.params.id);state.links=state.links.filter(l=>l.from!==q.params.id&&l.to!==q.params.id);save();r.sendStatus(204)});
app.post('/api/challenges/:id/links',(q,r)=>{const l={id:randomUUID(),challengeId:q.params.id,from:q.body.from,to:q.body.to};state.links.push(l);save();r.status(201).json(l)});
app.get('/api/network-models',(q,r)=>{const s=String(q.query.q||'').toLowerCase();r.json(!s?state.models:state.models.filter(m=>JSON.stringify(m).toLowerCase().includes(s)))});
app.post('/api/challenges/:cid/import/:mid',(q,r)=>{const m=state.models.find(x=>x.id===q.params.mid);if(!m)return r.sendStatus(404);const cur=state.nodes.filter(n=>n.challengeId===q.params.cid);const y=cur.length?Math.max(...cur.map(n=>n.y))+250:170;const imported=m.steps.map((s,i)=>({id:randomUUID(),challengeId:q.params.cid,type:s[0],title:s[1],body:s[2],x:70+i*240,y,sourceModelId:m.id}));state.nodes.push(...imported);for(let i=0;i<imported.length-1;i++)state.links.push({id:randomUUID(),challengeId:q.params.cid,from:imported[i].id,to:imported[i+1].id});save();r.status(201).json({model:m,imported})});
const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'});
app.use(vite.middlewares);
app.listen(PORT,'0.0.0.0',()=>console.log('RISE Project http://localhost:'+PORT));
